### PR TITLE
Support AnyScale

### PR DESCRIPTION
**Pull request by Colerar**
image

### CODE REVIEW

**Comment by forrestbao** [comment]
Thanks. My only concern is on `dotenv`. What is its purpose here?

**Comment by Colerar** [comment]
It loads .env file at working directory, just make debug easier.

**Comment by forrestbao** [comment]
Can we keep things simple and unique by only loading configurations from OS environmental variables?

**Comment by Colerar** [comment]
> Can we keep things simple and unique by only loading configurations from OS environmental variables?

The dotenv is simple enough. Basically `.env` is the same as bash export syntax, and as you can see, there is no complexity introduced in the code. There are only a import and a function call.

The main problem is that you can't re-enter the key every time, so saving a copy to disk is a natural idea.

**Comment by forrestbao** [comment]
I strongly prefer to use OS environment variable. It can be saved in files too and can be reactivated via `source`. My motive is to follow the convention in major GenAI APIs that the keys are stored in OS environment variables. 
Keeping one way is better than having multiple ways.

**Comment by Konoyoru435** [comment]
The huggingface inference now is supported in this PR, can you check it @forrestbao? Thank you so much.

**Pull request merged**
